# test
test :
 test :
  minlength :
   params : 5
   error_msg : Error!

# BuildMaster
insertBuildMaster :
 id :
  chkEngNum :
   error_msg : IDを英数字で再入力してください。
  minlength :
   params : 0
   error_msg : IDを入力してください。
 name :
  minlength :
   params : 0
   error_msg : ビル名を入力してください。
updateBuildMaster :
 id :
  chkEngNum :
   error_msg : IDを英数字で再入力してください。
  minlength :
   params : 0
   error_msg : IDを入力してください。
 name :
  minlength :
   params : 0
   error_msg : ビル名を入力してください。
deleteBuildMaster :
 id :
  chkEngNum :
   error_msg : ビルIDを英数字で再入力してください。

# RoomMaster
insertRoomMaster :
 build_id :
  unselected :
   error_msg : ビルを選択してください。
 name :
  minlength :
   params : 0
   error_msg : 会議室名を入力してください。
updateRoomMaster :
 name :
  minlength :
   params : 0
   error_msg : 会議室名を入力してください。
deleteRoomMaster :
 id :
  chkEngNum :
   error_msg : 会議室IDを英数字で再入力してください。

# ReserveInfo
insertReserveInfo :
 id :
  unselected :
   error_msg : 会議室を選択してください。
 username :
  minlength :
   params : 0
   error_msg : 会社名を入力してください。
updateReserveInfo :
 username :
  minlength :
   params : 0
   error_msg : 会社名を入力してください。
deleteReserveInfo :
 id :
  chkEngNum :
   error_msg : 会議室IDを英数字で再入力してください。